# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20171121_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='friends.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
